name: CI
permissions: {}
on:
- push
- pull_request
jobs:
  main:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
        - python-version: '3.8'
          os: ubuntu-22.04
          pyicu: pyicu==2.7
        - python-version: '3.9'
          os: ubuntu-22.04
        - python-version: '3.10'
          os: ubuntu-22.04
        - python-version: '3.11'
          os: ubuntu-22.04
        - python-version: '3.11'
          os: ubuntu-22.04
          unicodedata2: unicodedata2
        - python-version: '3.12'
          os: ubuntu-22.04
        - python-version: '3.13'
          os: ubuntu-24.04
        - python-version: '3.14'
          os: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key:
          pip-${{matrix.os}}-python${{matrix.python-version}}-${{matrix.unicodedata2}}
        restore-keys:
          pip-${{matrix.os}}-python${{matrix.python-version}}-
    - name: set up Python ${{matrix.python-version}}
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: apt install deps
      run: |
        sudo apt-get install doc-rfc-informational libuninameslist1 unicode-data
    - name: pip install wheel
      run: |
        python3 -m pip install wheel
    - name: pip install unicodedata2
      if: ${{matrix.unicodedata2}}
      run: |
        python3 -m pip install --verbose ${{matrix.unicodedata2}}
    - name: pip install PyICU
      run: |
        python3 -m pip install --verbose ${{matrix.pyicu || 'pyicu'}}
    - name: print version info
      run: |
        ./ult --version
    - name: run tests
      run: |
        make test
    - name: update generated code
      run: |
        private/update-gen-code
        git diff --exit-code
    - name: install
      run: |
        make install PREFIX=~/.local
    - name: post-install smoke-test
      run: |
        cd /
        ult --version
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: run pylint
      run: |
        python3 -m pip install pylint
        python3 -m pylint tests
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info README

# vim:ts=2 sts=2 sw=2 et
